#!/bin/bash
# Runs one or more INSTANCES as containers, with one compose file beside them.
#   ./scripts/install-docker.sh ~/.elixir-mcp-discord/myclan              one bot
#   ./scripts/install-docker.sh ~/.elixir-mcp-discord/{pk,shipit,ek}      several, one file
#   ./scripts/install-docker.sh ... --image 0.4.0     the published image, not this checkout
#   ./scripts/install-docker.sh ... --no-start        write compose.yml, start nothing
#   ./scripts/install-docker.sh ... uninstall         stop and remove the containers
#
# The instances must share a parent directory; compose.yml is written there,
# one service per instance, named after its directory. Pass EVERY instance
# each time: the file is regenerated, not merged. Nothing inside an instance
# changes — .env, config.json, agent/, state/ and its git history are mounted
# as they are — so going back to launchd or systemd is stopping the container
# and running that installer again.
#
# It refuses while a launchd job or systemd unit for the same instance is
# running: two processes on one bot token answer every question twice and
# write one state file between them. See docs/DOCKER.md.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE="ghcr.io/jthingelstad/elixir-mcp-discord"
BASE_LABEL="com.poapkings.elixir-mcp-discord"

ACTION="install"
START=1
TAG=""
INSTANCES=()
while [ $# -gt 0 ]; do
  case "$1" in
    install|uninstall) ACTION="$1" ;;
    --no-start) START=0 ;;
    --image) TAG="${2:?--image needs a version, e.g. 0.4.0}"; shift ;;
    *) INSTANCES+=("$(cd "$1" && pwd)") ;;
  esac
  shift
done
if [ ${#INSTANCES[@]} -eq 0 ]; then
  echo "usage: $0 <instance-dir>... [--image <version>] [--no-start] [uninstall]" >&2
  exit 2
fi

PARENT="$(dirname "${INSTANCES[0]}")"
for dir in "${INSTANCES[@]}"; do
  if [ "$(dirname "$dir")" != "$PARENT" ]; then
    echo "every instance must be in the same directory ($PARENT); $dir is not" >&2
    exit 1
  fi
done
COMPOSE="$PARENT/compose.yml"
MARKER="# generated by elixir-mcp-discord/scripts/install-docker.sh"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found: install Docker Desktop, OrbStack or Colima first (docs/DOCKER.md)" >&2
  [ "$START" = 0 ] || exit 1
fi

if [ "$ACTION" = "uninstall" ]; then
  names=()
  for dir in "${INSTANCES[@]}"; do names+=("$(basename "$dir")"); done
  docker compose -f "$COMPOSE" rm --stop --force "${names[@]}"
  echo "stopped and removed: ${names[*]} (the instance directories are untouched)"
  exit 0
fi

for dir in "${INSTANCES[@]}"; do
  name="$(basename "$dir")"
  if [ ! -f "$dir/.env" ]; then
    echo "no .env in $dir — run setup first (docs/DOCKER.md shows it inside the container)" >&2
    exit 1
  fi
  if [ "$(uname)" = "Darwin" ] && launchctl print "gui/$(id -u)/$BASE_LABEL.$name" >/dev/null 2>&1; then
    echo "$name is running under launchd; stop it first: ./scripts/install-launchd.sh $dir uninstall" >&2
    exit 1
  fi
  if command -v systemctl >/dev/null 2>&1 && systemctl --user is-active --quiet "elixir-mcp-discord-$name" 2>/dev/null; then
    echo "$name is running under systemd; stop it first: ./scripts/install-systemd.sh $dir uninstall" >&2
    exit 1
  fi
done

if [ -f "$COMPOSE" ] && ! head -1 "$COMPOSE" | grep -qF "$MARKER"; then
  echo "$COMPOSE exists and was not written by this script; move it aside first" >&2
  exit 1
fi

if [ -n "$TAG" ]; then
  SOURCE="  image: $IMAGE:$TAG"
else
  SOURCE="  image: elixir-mcp-discord:local
  build: $REPO"
fi

{
  echo "$MARKER"
  echo "# Re-run it with every instance rather than editing by hand. docs/DOCKER.md"
  echo "# explains each line; \`docker compose ps\` from this directory lists the bots."
  echo "name: elixir-mcp-discord"
  echo ""
  echo "x-bot: &bot"
  echo "$SOURCE"
  cat <<YAML
  # Brought back when it exits: a crash, a reboot of the Docker runtime, or
  # the bot restarting itself after a DM setting change (SERVICE_MANAGED=1
  # is set in the image).
  restart: unless-stopped
  # A tiny init as PID 1, so signals reach node and nothing is left behind.
  init: true
  # The host user that owns the instance: the bot reads its 0600 .env and
  # writes state/, config.json and agent/ as you.
  user: "$(id -u):$(id -g)"
  # On a stop the bot finishes the turn it is in (up to 45 s) before exiting.
  stop_grace_period: 60s
  # The log, rotated: 5 files of 10 MB per bot.
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

services:
YAML
  for dir in "${INSTANCES[@]}"; do
    name="$(basename "$dir")"
    echo "  $name:"
    echo "    <<: *bot"
    echo "    container_name: elixir-mcp-discord-$name"
    echo "    volumes:"
    echo "      - \"$dir:/instance\""
  done
} > "$COMPOSE"

echo "wrote $COMPOSE (${#INSTANCES[@]} bot(s))"
if [ "$START" = 0 ]; then
  echo "  start them:   docker compose -f $COMPOSE up -d --build"
  exit 0
fi

docker compose -f "$COMPOSE" up -d --build
echo ""
echo "running. From $PARENT:"
echo "  docker compose ps                     what is running"
echo "  docker compose logs -f <name>         one bot's log (Ctrl-C stops reading, not the bot)"
echo "  docker compose restart <name>         restart one bot"
echo "  docker compose up -d --build          after a code change in $REPO"
